name: Build Maven Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.devcontainer/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.devcontainer/**'
  workflow_dispatch:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      latest_tag:
        description: "The first job output"
        value: ${{ jobs.build.outputs.latest_tag }}
      latest_image:
        description: "The second job output"
        value: ${{ jobs.build.outputs.latest_image }}
env:
  SOURCE_REPOSITORY: 'gematik/ref-idp-server'
jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.tag.outputs.LATEST_TAG }}
      latest_image: ${{ steps.image.outputs.LATEST_IMAGE }}
    steps:
      - name: Checkout repository tag
        uses: actions/checkout@v4.2.2
        with:
          repository: ${{ env.SOURCE_REPOSITORY }}
          fetch-tags: 'true'
      - name: Set LATEST_TAG
        id: tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Check existing release
        id: check_release
        run: echo "NEW_RELEASE=$(gh release view ${{ steps.tag.outputs.LATEST_TAG }} --repo ${{ github.repository }} --json tagName --jq '.tagName' | cat && echo "false" || echo "true")" > $GITHUB_ENV
      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven (no tests)
        run: |
          mvn clean install -pl idp-server -am -Dskip.unittests -Dskip.inttests -Dcommit_hash=`git log --pretty=format:'%H' -n 1`
      - name: ${{ env.RELEASE_TAG }} Create Release
        id: create_release
        if: ${{ env.NEW_RELEASE }}
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.LATEST_TAG }}
          release_name: Release ${{ steps.tag.outputs.LATEST_TAG }}
          draft: false
          prerelease: false
      - name: ${{ env.RELEASE_TAG }} Upload Asset
        uses: softprops/action-gh-release@v2
        if: ${{ env.NEW_RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: idp-server-${{ steps.tag.outputs.LATEST_TAG }}.jar
          tag_name: ${{ steps.tag.outputs.LATEST_TAG }}
          repository: ${{ github.repository }}
          files: |
            /home/runner/work/idp-server/idp-server/idp-server/target/idp-server-${{ steps.tag.outputs.LATEST_TAG }}.jar
            /home/runner/work/idp-server/idp-server/idp-server/target/idp-client-${{ steps.tag.outputs.LATEST_TAG }}.jar
            /home/runner/work/idp-server/idp-server/idp-server/target/idp-commons-${{ steps.tag.outputs.LATEST_TAG }}.jar
            /home/runner/work/idp-server/idp-server/idp-server/target/idp-crypto-${{ steps.tag.outputs.LATEST_TAG }}.jar
      - name: Push to GHCR
        if: ${{ env.NEW_RELEASE }}
        env:
          LATEST_TAG: ${{ steps.tag.outputs.LATEST_TAG }}
        id: image
        run: |
          docker tag local/idm/idp-server:${{ steps.tag.outputs.LATEST_TAG }} ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.LATEST_TAG }}
          docker tag local/idm/idp-server:${{ steps.tag.outputs.LATEST_TAG }} ghcr.io/${{ github.repository }}:latest
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push --all-tags ghcr.io/${{ github.repository }}
          echo "LATEST_IMAGE=ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.LATEST_TAG }}" >> $GITHUB_OUTPUT